# Variable 'SolutionName' was defined in the Variables tab
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: vs2017-win2016
  steps:
  - checkout: self
  - task: PowerPlatformToolInstaller@0
    displayName: 'Power Platform Tool Installer '
  - task: PowerPlatformPackSolution@0
    displayName: 'Power Platform Pack Solution '
    inputs:
      SolutionSourceFolder: $(Build.SourcesDirectory)\$(SolutionName)
      SolutionOutputFile: $(Build.ArtifactStagingDirectory)\$(SolutionName)_managed.zip
      SolutionType: Managed
  - task: PublishPipelineArtifact@1
    displayName: Publish Pipeline Artifact
    inputs:
      path: '$(Build.ArtifactStagingDirectory)\$(SolutionName)_managed.zip '
      artifactName: drop
...
